import type { Metadata } from 'next'
import './assets/globals.css'
import { MenuProvider } from '@/Context/Menu'
import ToastProvider from '../../providers/ToastProvider'

export const metadata: Metadata = {
  title: 'suplayer panal',
  description: 'Generated by parseh groups',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fa'>
      <MenuProvider>
        <body>
          <ToastProvider />
          <main
            className={`w-full flex justify-between bg-gray-100 min-h-[100vh]`}>
            {children}
          </main>
        </body>
      </MenuProvider>
    </html>
  )
}
