import type { Metadata } from 'next'
import './assets//globals.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
import { MenuProvider } from '@/Context/Menu'
import ToastProvider from '../../providers/ToastProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <MenuProvider>
        <body>
        <ToastProvider />
          <main className={`w-full flex pt-3`}>
            <Sidebar />
            <div className={'w-[80%] mr-[22%]'}>
              <Header />
              {children}
            </div>
          </main>
        </body>
      </MenuProvider>
    </html>
  )
}